### ISSUE TITLE
2.0 Not exporting all tracks

### ISSUE THREAD

**Issue by mhatsis** [r0x0r/traktorlibrarian#3]
How's it going? very handy program and thanks for making it.
  When I export to USB Drive, It only exports some of my tracks, all playlists seem to be there, but there are alot of tracks missing. Also, the tracks are in a hidden folder named '.Music'

I'm on Traktor 2.81 and OS X Yosemite
Also, I tried the command line version w python 2.7.10
didn't do anything. not really too good w command line tho
anyway, please let me know, would love to get this going. also, if you need any more info let me know
Cheers,
Michael

**Comment by r0x0r** [comment]
Hey Michael,
The .Music directory is hidden by design in order to stay hidden in Traktor Explorer tree. I've been thinking of a use case to make it visible, but still have not come up with anything.

As for the exporting problem, can you provide a log that is generated when you export your collection (open Application -> Consol ).
To be honest the export functionality is buggy, but seeing as there is demand for it, I will look into fixing it.
